In [13]:
import numpy as np
from numpy import random 
X = np.array([[1,1],[2,2],[3,3],[4,4],[5,5]])
random.shuffle(x)
x

array([[2, 2],
       [4, 4],
       [3, 3],
       [5, 5],
       [1, 1]])

In [6]:
def _gini(y):
    '''
    INPUT:
        - y: 1d numpy array
    OUTPUT:
        - float

    Return the gini impurity of the array y.
    '''

    samp = y.shape[0]
    summ = 0
    summ2 = 0

    for class_i in np.unique(y): # [1,2,3]
        prob = sum(y == class_i) / float(samp)
        summ += prob**2
        summ2 += prob * (1-prob)
    return 1 - summ, summ2

_gini(x)

(0.5123966942148761, 0.5123966942148761)

In [19]:
def shuffle_split_data(X):
    arr_rand = np.random.rand(X.shape[0])
    split = arr_rand < np.percentile(arr_rand, 70)

    X_train = X[split]
    y_train = y[split]
    X_test =  X[~split]
    y_test = y[~split]

    print len(X_Train), len(y_Train), len(X_Test), len(y_Test)
    return X_train, y_train, X_test, y_test
    return X, arr_rand, X.shape[0]
shuffle_split_data(X)

(array([[1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]]),
 array([0.67774208, 0.36044142, 0.88329015, 0.72616392, 0.52491426]),
 5)

In [28]:
np.percentile(np.random.rand(5),70)

0.7603928001983322